# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/market_data.proto\x12\x0boneterminal\"d\n\nTickUpdate\x12\x0b\n\x03uId\x18\x01 \x01(\t\x12\x0b\n\x03ltp\x18\x02 \x01(\x02\x12\x0b\n\x03\x63hg\x18\x03 \x01(\x02\x12\x0c\n\x04\x63hgp\x18\x04 \x01(\x02\x12\t\n\x01v\x18\x05 \x01(\x04\x12\n\n\x02ts\x18\x06 \x01(\x04\x12\n\n\x02\x63p\x18\x07 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKUPDATE']._serialized_start=40
  _globals['_TICKUPDATE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
